# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-09 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devotions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devotion',
            name='edit_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='devotion',
            name='verse_end',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
