# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devotions', '0002_auto_20170909_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devotion',
            old_name='verse_start',
            new_name='verse_id',
        ),
        migrations.RemoveField(
            model_name='devotion',
            name='verse_end',
        ),
    ]
