# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BibleVersionKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.TextField()),
                ('abbreviation', models.TextField()),
                ('language', models.TextField()),
                ('version', models.TextField()),
                ('info_text', models.TextField()),
                ('info_url', models.TextField()),
                ('publisher', models.TextField()),
                ('copyright', models.TextField()),
                ('copyright_info', models.TextField()),
            ],
            options={
                'db_table': 'bible_version_key',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='KeyEnglish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b', models.IntegerField()),
                ('n', models.TextField()),
            ],
            options={
                'db_table': 'key_english',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TAsv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b', models.IntegerField()),
                ('c', models.IntegerField()),
                ('v', models.IntegerField()),
                ('t', models.TextField()),
            ],
            options={
                'db_table': 't_asv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TBbe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b', models.IntegerField()),
                ('c', models.IntegerField()),
                ('v', models.IntegerField()),
                ('t', models.TextField()),
            ],
            options={
                'db_table': 't_bbe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TDby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b', models.IntegerField()),
                ('c', models.IntegerField()),
                ('v', models.IntegerField()),
                ('t', models.TextField()),
            ],
            options={
                'db_table': 't_dby',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TKjv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b', models.IntegerField()),
                ('c', models.IntegerField()),
                ('v', models.IntegerField()),
                ('t', models.TextField()),
            ],
            options={
                'db_table': 't_kjv',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TWbt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b', models.IntegerField()),
                ('c', models.IntegerField()),
                ('v', models.IntegerField()),
                ('t', models.TextField()),
            ],
            options={
                'db_table': 't_wbt',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TWeb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b', models.IntegerField()),
                ('c', models.IntegerField()),
                ('v', models.IntegerField()),
                ('t', models.TextField()),
            ],
            options={
                'db_table': 't_web',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TYlt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b', models.IntegerField()),
                ('c', models.IntegerField()),
                ('v', models.IntegerField()),
                ('t', models.TextField()),
            ],
            options={
                'db_table': 't_ylt',
                'managed': False,
            },
        ),
    ]
